version: '3'

services: 
  api: 
    build: 
      context: ../../api
      dockerfile: ./docker/dev/Dockerfile
    volumes:
      - ../../api/src:/home/drinks/src
    restart: always
    networks:
      - postgre_network
      - nginx_network
    env_file:
      - ./.env.dev