version: '3'

services: 
  api: 
    build: 
      context: ../../api
      dockerfile: ./docker/prod/Dockerfile
    restart: always
    networks:
      - postgre_network
      - nginx_network
    env_file:
      - ./.env.prod