# Generated by Django 4.1.4 on 2023-01-23 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drinks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="name",
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
