# Generated by Django 4.1.4 on 2023-01-23 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drinks", "0002_alter_ingredient_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cocktailingredient",
            name="measure",
            field=models.CharField(max_length=32, null=True),
        ),
    ]
