# Generated by Django 4.1.4 on 2023-01-31 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("drinks", "0003_alter_cocktailingredient_measure"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cocktailingredient",
            name="cocktail",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ingredients",
                to="drinks.cocktail",
            ),
        ),
        migrations.AlterField(
            model_name="cocktailingredient",
            name="ingredient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ingredients",
                to="drinks.ingredient",
            ),
        ),
    ]
